### ISSUE TITLE
Android auto stopped working in latest  experimental release

### ISSUE THREAD

**Issue by wjvdb** [damianmqr/A9PatchingService#20] opened 2024-08-01 07:45 UTC
So far the [experimental build](https://xdaforums.com/t/hisense-a9-root-reward-offered-snapdragon-662.4495809/post-89627731) seems fine to me, there is however a problem with android auto at the moment. 
Both wired as wireless don't appear to work, even after deinstalling updates and reinstalling them. On unknown cars/android auto connections it will show the setup screen, but past that it goes blank and shuts of. for now I downgraded again to the previous version.  As I need to use my android auto often I can't unfortunately provide logging.  (except for coming sunday if it isn't resolved yet)

**Comment by wjvdb** [comment] 2024-08-03 07:48
Same issue looks to be still present in last Thursdays release. (I only tested it on head unit reloaded. Not yet in my car) Tomorrow I'll investigate it deeper and hopefully generate some logs etc.

**Comment by damianmqr** [comment] 2024-08-05 11:06
Should be resolved in latest commit, it was caused by a null pointer when attaching a secondary display (like Vysor or Android Auto)

**Closed by damianmqr** 2024-08-05 11:06 UTC
